import { escapeHtml } from "../common/pdf/pdf-renderer.service";

export interface PrescriptionPdfItem {
  medicineName: string;
  dosage: string;
  frequency: string;
  durationDays: number;
  specialInstructions: string | null;
  quantityPrescribed: number;
}

export interface PrescriptionPdfData {
  prescriptionId: string;
  hospitalName: string;
  doctorName: string;
  doctorSpecialization: string;
  doctorLicenseNumber: string;
  patientName: string;
  patientDob: string | null;
  patientGender: string | null;
  createdAt: string;
  items: PrescriptionPdfItem[];
  signatureUrl: string | null;
  supersedesId: string | null;
}


/** Renders the letterhead + item table + signature overlay HTML that
 * `PrescriptionPdfProcessor` feeds to Puppeteer (FR-RX-003). Kept as plain
 * inline-styled HTML with no external stylesheet/font requests — Puppeteer
 * has to fetch every referenced resource over the network before it can
 * render a stable PDF, and the only resource this template ever needs is
 * the doctor's own signature image (already same-origin-reachable via the
 * app's own S3/LocalStack endpoint). */
export function renderPrescriptionHtml(data: PrescriptionPdfData): string {
  const rows = data.items
    .map(
      (item) => `
      <tr>
        <td>${escapeHtml(item.medicineName)}</td>
        <td>${escapeHtml(item.dosage)}</td>
        <td>${escapeHtml(item.frequency)}</td>
        <td>${item.durationDays} day(s)</td>
        <td>${item.quantityPrescribed}</td>
        <td>${item.specialInstructions ? escapeHtml(item.specialInstructions) : "—"}</td>
      </tr>`,
    )
    .join("");

  const signatureBlock = data.signatureUrl
    ? `<img src="${data.signatureUrl}" alt="Doctor signature" style="max-height: 60px;" />`
    : `<div style="font-style: italic; color: #555;">Signature on file: Dr. ${escapeHtml(data.doctorName)}</div>`;

  const supersedesBlock = data.supersedesId
    ? `<p style="color: #a00; font-size: 12px;">Correction — supersedes prescription ${escapeHtml(data.supersedesId)}.</p>`
    : "";

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  body { font-family: Helvetica, Arial, sans-serif; color: #111; padding: 32px; }
  h1 { font-size: 20px; margin-bottom: 0; }
  .meta { font-size: 12px; color: #444; margin-bottom: 24px; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; }
  th, td { border: 1px solid #ccc; padding: 6px 8px; font-size: 12px; text-align: left; }
  th { background: #f2f2f2; }
  .footer { margin-top: 48px; display: flex; justify-content: space-between; align-items: flex-end; }
</style>
</head>
<body>
  <h1>${escapeHtml(data.hospitalName)}</h1>
  <div class="meta">
    Prescription ${escapeHtml(data.prescriptionId)} — ${escapeHtml(data.createdAt)}<br/>
    Dr. ${escapeHtml(data.doctorName)} (${escapeHtml(data.doctorSpecialization)}, Lic. ${escapeHtml(data.doctorLicenseNumber)})<br/>
    Patient: ${escapeHtml(data.patientName)}${data.patientDob ? ` — DOB ${escapeHtml(data.patientDob)}` : ""}${data.patientGender ? ` — ${escapeHtml(data.patientGender)}` : ""}
  </div>
  ${supersedesBlock}
  <table>
    <thead>
      <tr><th>Medicine</th><th>Dosage</th><th>Frequency</th><th>Duration</th><th>Qty</th><th>Instructions</th></tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="footer">
    <div style="font-size: 11px; color: #777;">Generated by MedCore HMS</div>
    <div style="text-align: center;">
      ${signatureBlock}
      <div style="font-size: 11px; border-top: 1px solid #333; padding-top: 4px;">Doctor's Signature</div>
    </div>
  </div>
</body>
</html>`;
}
